"""01_initial-db

Revision ID: 92c843825b65
Revises: 
Create Date: 2023-05-28 15:40:16.303471

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '92c843825b65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('original_url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('short_id', sa.String(length=8), nullable=False),
    sa.Column('short_url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('del_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_url_short_id'), 'short_url', ['short_id'], unique=False)
    op.create_table('short_url_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_url', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.String(length=50), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['short_url'], ['short_url.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_url_history_used_at'), 'short_url_history', ['used_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_url_history_used_at'), table_name='short_url_history')
    op.drop_table('short_url_history')
    op.drop_index(op.f('ix_short_url_short_id'), table_name='short_url')
    op.drop_table('short_url')
    # ### end Alembic commands ###
